//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab3_binding_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int ID { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventPlace { get; set; }
        public bool IsNotification { get; set; }
        public Nullable<int> RemindTime { get; set; }
        public string TypeOfTime { get; set; }
        public Nullable<bool> IsRepeat { get; set; }
        public Events(string _EventName, string _EventDescription, string _EventPlace, string _SelectedTume, int _RemindTime, bool _IsNotification, bool _IsRepeat, DateTime _EventDate)
        {
            EventName = _EventName;
            EventDescription = _EventDescription;
            EventPlace = _EventPlace;
            RemindTime = _RemindTime;
            TypeOfTime = _SelectedTume;
            IsNotification = _IsNotification;
            IsRepeat = _IsRepeat;
            EventDate = _EventDate;
        }
    }
}
